--- 
username: api-test@emeryco3.com
environment: development
subdomain: emeryco3-test
password: 1340b1d2212043febc33c5ef7dd238f5 
private_key: 0812ea5c916d409a83b35d106f1f52b1
site: https://api-production.recurly.com
